api_platform:


    title: 'API BusTrack V1'

    version: '0.0.1'

    show_webby: false

    openapi:
        contact:
            email: "azizkamadou17@gmail.com"
            name: "KAMAGATE Amadou Aziz"

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
